### ISSUE TITLE
Interesting race condition (not really a simple-translator bug, just wondered if you have thoughts)

### ISSUE THREAD

**Issue by gwprice115** [andreasremdt/simple-translator#21]
In our site there's a scroll behavior that's triggered on `load` whenever a url is loaded at a specific section id (e.g. a link to `index.html#contact` is clicked). We noticed that in English the scroll behavior always worked perfectly, but in German sometimes it did and sometimes it didn't, depending on whether it was being loaded from `localhost`.

The root cause is a race condition between when the translation is applied and when the `load` event in jquery is triggered. If `load` is triggered first, the underlying section positions (which happen to be in English) are used to scroll, so the page scrolls to a seemingly random position on the German site. If the translation is applied first, `load` works perfectly for the German page.

I hacked around this by moving the load logic into 
```
translator.fetch(['en', 'de']).then(() => {
  translator.translatePageTo();
  doScrollBehavior();
});
```
which feels wrong because it has nothing to do with translation, but it seems like the only way to guarantee the event happen _after_ translation.

Just wanted to let you know about this in case you have ideas about a better way to handle it. I had an idea that it might be useful to be able to listen to the translation event in case you want to chain some unrelated behavior like this after translation, but that would probably be hard to implement. Feel free to close this issue whenever.

**Comment by andreasremdt** [comment]
So I guess this is due to the fact that you fetch the JSON translations, which is an async operation. It would help me a lot in understanding your problem better if I'd have a demo or link to your site, could you provide one?

For now, I have a few ideas:

* Depending on how big the translations are and what underlying build environment you use, have you considered adding the translations using `translator.add()` instead of fetching them? This could avoid such race conditions because it's a synchronous action.
* Would it be an option to put the translator's logic inside the `load` event callback? Meaning that you use the translator, its languages, and the translation itself only after the page has been finished loading? On the other hand, this could lead to flashy text, which I understand might not be very pleasant to look at.
* Adding such an event to the translator library wouldn't be a big issue for me, but I'd like to know more about the use-case first, that's why I asked you if you could provide a link to your website.

**Comment by andreasremdt** [comment]
Hm, I couldn't reproduce the issue that you described, but I get your point. 

First, I have a suggestion for your code on line 15 - 30:
```js
function changeLang() {
  var targetLanguage = document.documentElement.lang === 'en' ? 'de' : 'en';

  translator.fetch(targetLanguage).then(() => {
    translator.translatePageTo(targetLanguage);
  });

  // close menu if it's open (mobile only)
  ...
  }
}
```

I saw that you always fetch both language files, but in reality, you only need one of them at that moment. If the user switches the language, you can then still go ahead and fetch the other one. But this way, you don't load any resources the user won't need anyway.

Regarding the issue with the scrolling, I don't see any problem with where your code is located. I think that in that case, it's fine in the callback. Alternatively, you could use `async/await` to not have the callback.

```js
(async function() {
  await translator.fetch(['de', 'en']);

  translator.translatePageTo();
  scrollToProperSection();
})();
```

One thing to note with using `await` is that you need to wrap your entire code with an async function, that's just how it is at the moment.

**Comment by gwprice115** [comment]
awesome thanks for the suggestions! will do both

**Comment by andreasremdt** [comment]
Cool, glad that I could help :)

One last thing I noticed on your website was that you didn't transpile your JavaScript into ES5. Just as a tip, if you want to make your website as accessible as possible (also to users with older browsers), I'd recommend using a transpiler like Babel in combination with Webpack or Rollup, so that you get to write the latest JavaScript but all of your users can interact with the website. But that's optional of course, whatever you prefer ;)
