### ISSUE TITLE
Translate data atributes and images

### ISSUE THREAD

**Issue by joaodoxy** [andreasremdt/simple-translator#22]
Hello,

Thanks for your package.

I have 2 questions.

1 - How i can change a data atribute? Because im using  magnific popup for videos
**data-mfp-src="assets/videos/video_en.mp4"**
But i need to change a link if is En or other language.,
How i can do it?

2 - The last question is about images. How i can change an image, depending on the active language.
In english the image for EN if for example ES other image.
How i can do it?

Thanks a lot

**Comment by andreasremdt** [comment]
I just looked at your code example and there are a few things that could be improved. But I also saw that I have some piece of logic in my library that could be improved.

When using the `detectLanguage` option, I would assume that the translator returns the detected language using `translator.currentLanguage`, but that's not the case. I will fix this bug as soon as possible and send a code example for your website that you can use.

**Comment by joaodoxy** [comment]
Thanks @andreasremdt 

And about your piece of code? is it ok to use that way all the time? always that i need to change the language? becasue in v1 i used it in other  way
```
translator.fetch(['en', 'de']).then(() => {
        translator.translatePageTo(current_lang);
    });
```

**Comment by andreasremdt** [comment]
Hello @joaodoxy 

Regarding your last question: you don't need to fetch all languages every time you use the translator. You could solve this through 2 different approaches:

1. Fetch both languages after page load and then use them (useful when you need to switch languages many times)
```js
await translator.fetch(['en', 'de']);

// Now you have both languages available and can use them whenever you want
translator.translatePageTo(current_lang);

function toGerman() {
  translator.translatePageTo('de');
}
// etc...
```

2. Or, you only fetch the language that's needed at the time. This might be the more useful approach, because users usually don't translate a page that many times.

```js
translator.fetch(current_lang).then(() => {
  translator.translatePageTo(current_lang);
});
```

One downside of the second approach is that languages are not cached, meaning that the user might have duplicated network requests if they translate your page often, but I plan to fix that soon.

**Comment by andreasremdt** [comment]
> @andreasremdt ahh ok so i need to update my code. About the ** was the markdown.
> 
> I have a menu with language option, and when you choose a language im saving it in a localstorage too.
> 
> But with new v2 i think that im not using in the good way. Because iam fetching all the time.
> 
> Can you help me and fix my code please (can you send me a new pastebin fixed) ? can yo uhave a look? look my code:
> ( I dont know if the other things are very well implemented, but i think its ok. )
> 
> https://pastebin.com/Hpt0YEhg

Regarding the code snippet that you provided in this reply I saw a few issues that I tried to fix:

```js
const translator = new Translator({
    persist: false,
    languages: ["de", "en"],
    defaultLanguage: "en",
    detectLanguage: true,
    filesLocation: "/assets/i18n"
});

function translate(lang) {
    translator.fetch(lang).then(() => {
        translator.translatePageTo(lang);
    });
 
    removeActiveClass();
    document.getElementById("lang-" + lang).classList.add("active-lang");
}

const urlParameter = getUrlParameter('lang');

// This means that the URL parameter language was provided
if (urlParameter) {
  translate(urlParameter);
} else if (translator.currentLanguage != 'en') {
  // This means that the user prefers a different language
  translate(translator.currentLanguage);
}
```

1. You had the same code repeated a few times, I extracted that into a function `translate`.
2. You always fetched both languages, although only one was needed. I changed that as well.
3. You did some stuff that the translator can now do, like detecting the user's language from the browser or local storage. I changed the script accordingly. In the condition `translator.currentLanguage != 'en'` I assume that your default language is `en`. If the translator runs and you provide the `detectLanguage` option, it can automatically detect the user's preferred language, and if that's `de` for example, this condition would be truthy and hence it would be able to run.
4. Since you also parse some URL query parameter, I thought that this might have precedence, so this logic is handled in the first if-condition.

**Note that you have to download simple-translator@2.0.3 for this in order to make it work**. I fixed an issue in the language detection and released this version today.

**Comment by andreasremdt** [comment]
This issue has been closed automatically because I merged the PR. Please let me know if this helps you @joaodoxy  :)
