### ISSUE TITLE
fetch will get en.json as HTML not json

### ISSUE THREAD

**Issue by anton-rs** [andreasremdt/simple-translator#26]
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
Promise.then (async)
parcelRequire.js/i18n.js.@andreasremdt/simple-translator @ i18n.js:10
newRequire @ i18n.f855dee8.js:47
(anonymous) @ i18n.f855dee8.js:81
(anonymous) @ i18n.f855dee8.js:120

When I see the network tab, it shows that en.json detected as HTML not JSON.
I think this is the reason why the error happen

**Comment by andreasremdt** [comment]
Could you please elaborate a bit further on the config of Simple Translator (especially the `filesLocation` option) and how your files are organized?

Usually, Simple Translator fetches a file based on the given path and name, for example `./i18n/en.json`. I find it a bit strange that the file is detected as HTML. Also, judging from the error message, it seems that the content is indeed HTML, otherwise, it wouldn't run into the SyntaxError.

I am happy to look into the problem with a bit more information about your setup :)

**Comment by anton-rs** [comment]
It was because I'm try using the code from sandbox, maybe it was outdated, but it's working for now. thanks :+1:
