### ISSUE TITLE
Question: Is it SEO friendly?

### ISSUE THREAD

**Issue by pa-dieter** [andreasremdt/simple-translator#36]
How does google robot see the site? In english or german or spanish?

**Comment by andreasremdt** [comment]
That depends more or less on your configuration (e.g. when the page is translated).
First, it's a best practice to use a fallback language, even before the translator kicks in. Looking at this code example

```html
<p data-i18n="text">some fallback text</p>
```

you'd have _some fallback text_ as the default text, which is displayed when the page is initially rendered. This is also what Google's Bot would see. If you'd leave it empty, like 

```html
<p data-i18n="text"></p>
```

then I would expect some SEO issues, yes.

What happens next depends on whether or not you translate the page automatically on page load. If so, I am not entirely sure what Google's Bot would see, but I assume it's the text that got rendered out initially, not the applied translation.

Generally speaking, there are lots of SEO pitfalls when implementing translations. As an example, it's recommended to use different URLs for different languages, like `website.com/en/` or `en.website.com`.

Maybe you'll find [this thread](https://stackoverflow.com/questions/1828317/internationalization-and-search-engine-optimization) helpful, it gave me some insights on how these things should be handled.

Otherwise, if you have some more questions, feel free to drop them here!
