### ISSUE TITLE
Lit-Element usage

### ISSUE THREAD

**Issue by inguser** [andreasremdt/simple-translator#5]
Is it possible to use the translator in a Lit-Element web component.
The html is in the render method and I can't get it working, I think because the html is in the shadow dom.

Thnx!

**Comment by andreasremdt** [comment]
Hi @inguser, could you please provide me an example on how you are using the library? That would help me figure out why it's not working.

**Comment by inguser** [comment]
Hi,

I tried the following code:

`import { LitElement, html } from 'lit-element';
import Translator from "./translator.js";

class TransElement extends LitElement {

    constructor() {
        super();
        this.init();
    }

    static get properties() {
        return {
            translator: {
                type: Translator
            }
        };
    }

    init() {
        this.translator = new Translator({
            persist: true,
            languages: ["de", "en", "nl"],
            defaultLanguage: "en",
            detectLanguage: true,
            filesLocation: "/i18n",
        });
        this.translator.load("nl");
    }

    render() {
        return html`
        <header>
        <h1 data-i18n="header.title">Translate me</h1>
        </header>
         `;
    }
}

customElements.define('trans-element', TransElement);
`

**Comment by inguser** [comment]
Hi, found a workaround. But it would be nice that I could use the data-i18n.

Workaround:

`
import { LitElement, html } from 'lit-element';
import Translator from "./translator.js";

class TransElement extends LitElement {

    constructor() {
        super();
        this.init();
    }

    static get properties() {
        return {
            translator: {
                type: Translator
            },
            transText: {
                type: String
            }
        };
    }

    init() {
        this.translator = new Translator({
            persist: true,
            languages: ["de", "en", "nl"],
            defaultLanguage: "en",
            detectLanguage: true,
            filesLocation: "/i18n",
        });
        this.translator
            .getTranslationByKey("nl", "header.title")
            .then((translation) => this.setText(translation));
    }

    setText(text) {
        this.transText = text;
    }

    render() {
        return html`
        <header>
        <h1>${this.transText}</h1>
        </header>
         `;
    }
}

customElements.define('trans-element', TransElement);


`

**Comment by andi34** [comment]
@inguser not sure if it helps but this is how I've implemented simple-translator for a Photobooth project I am working on:
https://github.com/andi34/photobooth/pull/48/files

**Comment by andreasremdt** [comment]
Hey @inguser, I finally had the time to look into your issue. As you already suspected, the translation didn't work due to the fact that `lit-element` uses Shadow DOM by default. In this case, `document.querySelectorAll` (which this library uses) doesn't work, because it doesn't penetrate the Shadow DOM by default.

I came around with this workaround:

```js
function getElementsInsideShadowDOM(elements) {
        var matches = [];

        document.querySelectorAll(elements.join(',')).forEach((element) => {
          if (element.shadowRoot) {
            var found = Array.from(
              element.shadowRoot.querySelectorAll('[data-i18n]')
            );

            matches.push(...found);
          }
        });

        return matches;
      }

new Translator({
  selector: getElementsInsideShadowDOM(['trans-element', 'some-element']),
 });
```

The trick here is that Simple Translator can take a `selector` option, which overrides the default mechanism. You can pass a DOMList or an array of items that you want to translate. Using the helper function `getElementsInsideShadowDOM`, you can retrieve all elements that have the `data-i18n` attribute (or any other attribute for that matter, just change the code) and pass them to the translator, making them in fact translatable.

I tested around locally and it worked fine, could you imagine using this solution in your project?

**Note:** this solution requires v2 of the simple-translator installed, not v1.

**Comment by andreasremdt** [comment]
Here's a full demo implementation of the translator with LitElement:
https://codesandbox.io/s/simple-translator-lit-element-bkfon

 Unfortunately it's a bit of a hack because LitElement renders the HTML asynchronously, so I needed to wrap the translator in some helper functions. Hope this helps!
