### ISSUE TITLE
Pure Javascript not working due to import

### ISSUE THREAD

**Issue by DonHaul** [andreasremdt/simple-translator#81]
Hi, I donwloaded the code from https://codesandbox.io/s/simple-translator-vanilllajs-e33ye

and ran it locally, and it does not translate, the error is import statement outside module see below,
![image](https://user-images.githubusercontent.com/13081142/120908792-208ce300-c666-11eb-88bb-b8840ca9f44f.png)

**Comment by andreasremdt** [comment]
Hi! Yes, this won't work, because the source code in this example is using EcmaScript Modules and needs to be bundled with a module bundler like Webpack or Rollup.

There are two things you can do:
1. Use the [installation guide](https://github.com/andreasremdt/simple-translator#installation) from the README instead, you can either install the translator via NPM or use the CDN link as described.
2. If you don't want to add a module bundler to the downloaded example, you can add `type="module"` to the `script` tag that imports the translator (index.html:47):
```html
<script src="js/index.js" type="module"></script>
```
Please note that this is not recommended in a production environment, though.

**Comment by DonHaul** [comment]
Thanks! yes I will add `type="module"` to my script, thank you very much!
